### ISSUE TITLE
Rename this repo to just 'documentation' or 'docs'

### ISSUE THREAD

**Issue by leifmadsen** [redhat-service-assurance/documentation#28]
I'd like to rename this repo to just `documentation` or `docs` since the path to reading this documentation is based on the repo.

Going to https://redhat-service-assurance.github.io/docs or https://redhat-service-assurance.github.io/documentation seems neater than using https://redhat-service-assurance.github.io/saf-documentation

**Comment by JoanneOFlynn2018** [comment]
Makes good sense Leif!
